#version: '3'

services:
  mysql:
    image: elestio/mysql:8.0
    restart: always
    hostname: mysql
    volumes:
      - ./storage/mysql:/var/lib/mysql
    ports:
      - "50778:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  glpi:
    build:
      context: .
      args:
        SOFTWARE_VERSION_TAG: ${SOFTWARE_VERSION_TAG}  # Pasar la variable al Dockerfile
    restart: always
    hostname: glpi
    ports:
      - "22571:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./storage/var/www/html/glpi/:/var/www/html/glpi
    environment:
      - TIMEZONE=America/Asuncion
      
  pma:
    image: phpmyadmin
    restart: always
    links:
      - mysql:mysql
    ports:
      - "22811:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}  # Usa MYSQL_ROOT_PASSWORD
      - UPLOAD_LIMIT=500M
      - MYSQL_USERNAME=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}  # Usa MYSQL_ROOT_PASSWORD
    depends_on:
      - mysql
  
networks:
  docker01-services:
    external: true
